### PR TITLE
Fix render layers

### PR DESCRIPTION
**Pull request by ChristopherBiscardi**
This is a rebased version of #49 which looks like it only needed merge conflicts resolved

### CODE REVIEW

**Comment by simbleau** [comment]
Hey Chris! Thanks for the assist. I'll take a look shortly.

**Comment by simbleau** [comment]
This almost works. I'll probably commit to this branch if that's ok with you, Chris. This is a good base.
image

**Comment by ChristopherBiscardi** [comment]
@simbleau totally cool with me!

**Comment by simbleau** [comment]
This is stickier than I thought. See #58 for additional discussion.

Nonetheless, I'm making progress.

**Comment by simbleau** [comment]
@ChristopherBiscardi

Render layers have been obeyed, there's a new `render_layers` example that uses Gizmos and render layers as well. Feel free to bend it to your will and let me know if behavior is as you expect.

image

**Review by simbleau — APPROVED** [review]

**Comment by ChristopherBiscardi** [comment]
awesome! thank you! I'll let you know how it goes.

**Pull request merged**
